###
GET http://localhost:4000/api/platillos

###
GET http://localhost:4000/api/pedidos

###
POST 

###
POST http://localhost:4000/api/pedidos
Content-Type: application/json
{

    "alimentoconsumir": "Pizza",
    "cantidad": 2,
    "precio_alimento": "20.99",
    "bebida": "Coca Cola",
    "cantidad_bebida": 3,
    "precio_bebida": "2.50",
    "tipopago": "Tarjeta",
    "propina": "5.00",
    "numeromesa": 1,
    "estatus": "pendiente",
}

###
GET http://localhost:4000/api/usuariossuarios

###
GET http://localhost:4000/api/usuarios

###
PUT http://localhost:4000/api/pedidos/4
Content-Type: application/json

{
    "idcomanda": 1,
    "nombrecliente": "Miguelito",
    "alimentoconsumir": "Hamburguesita",
    "cantidad": 2,
    "bebida": "Beer",
    "cantidadbebida": 1
}

###
DELETE http://localhost:4000/api/pedidos/11